### ISSUE TITLE
Still taking way to long to finalize files

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#122]
The program is still taking like 15 to 20 min to finalize files after you get 100% download is their any way to speed this up??

**Comment by shinigamichan** [comment]
@DJboutit Are you trying to save to a network drive or something? The way this program is designed to store chunks makes it very inefficient when used in a such a matter. 
The easiest way to address this would be a feature that stores the chunks locally and then moves the file to a different location after it's complete. See, for example https://github.com/tonikelope/megabasterd/issues/44#issuecomment-476484980
You need to post details of your platform and filesystem type in order to make a useful report.

**Comment by DJboutit** [comment]
No I am saying files to my main driver with windows.

**Comment by tonikelope** [comment]
> @DJboutit Are you trying to save to a network drive or something? The way this program is designed to store chunks makes it very inefficient when used in a such a matter.
> The easiest way to address this would be a feature that stores the chunks locally and then moves the file to a different location after it's complete. See, for example [#44 (comment)](https://github.com/tonikelope/megabasterd/issues/44#issuecomment-476484980)
> You need to post details of your platform and filesystem type in order to make a useful report.

That is indeed the case.

> No I am saving files to my main drive with windows.

 I can't think what might be happening to you. I recommend that you save the chunks on a fast hard drive and limit simultaneous downloads (and watch other applications that write/lean from the hard drive while using MegaBasterd). I'm sorry I can't help any more.

Regards
