### ISSUE TITLE
Can't download, even with smartproxy on.

### ISSUE THREAD

**Issue by Succhihahaha** [tonikelope/megabasterd#255]
So I put all the proxies, but once download gets stalled, it just won't restart. Does it have to do with the file size? I'm downloading a +15 gb mp4 video.

**Comment by retraenn** [comment]
I have the same issue, it works using a network wide VPN installed in Windows but the proxy setting, even with manual proxy information like you said, doesn't seem to work anymore. There haven't been any updates for a while which is a little disappointing because other mega downloaders don't allow streaming while downloading and some other features.

Are any further updates or fixes planned @tonikelope ? If not I still appreciate the work that was put into this app in the past <3

**Comment by j0k4rX** [comment]
i am having the same problem here! Help!!!

**Comment by tonikelope** [comment]
Hello to all. As I have said many times, proxies are a halfway solution and they don't work sometimes. They have to be tested proxies to download from MEGA (not all of them work), and also be fast and not saturated (or without quota). The more people use the same proxies as you, the less time you will have to take advantage of them. There are many proxies on Google. It's a matter of searching.

**Comment by j0k4rX** [comment]
How to test proxies for mega @tonikelope ? & why don't u add a vpn service to megabastard ? there are many free vpn online (like:- protonvpn), and plz plz add a switcher to change ip automatically in X minutes! 
Thanks.

**Comment by tonikelope** [comment]
MegaBasterd will not include proxies or VPN clients. I have my reasons for not doing so.

On the switch, in advanced settings you can include a command to be launched when the MEGA download limit is reached. That command can be anything (reset the router, activate an external VPN, etc.)

There is no need to test the proxies because MegaBasterd temporarily discards proxies that give errors although that can make the download fluctuate more than if the proxy list only includes fast proxies.

Greetings.

**Comment by j0k4rX** [comment]
Hi again @tonikelope , recently i tried to download 70gb+ mega files with proxies on (for at least 12hours+ long). And the problem is -> i couldn't even download files over 70mb. All that happens is the files are downloaded (like:60mb) and downloaded files are auto-deleted & comes back to 20. And this process continues with no progress.
So any solutions to it plz? Thanks.

**Comment by tonikelope** [comment]
As I have already said the use of proxies and many simultaneous transfers makes megabasterd unstable when making many connection and reconnection attempts. Also, if a download remains more than 5 minutes without receiving data it self-resets (and some progress may be lost). Try to lower the number of simultaneous transfers (and slots) or use better proxies (or a paid VPN).

Regards.

**Comment by azee007** [comment]
the download speed is very slow even though i have a very stable internet connection at the start of download the speed is good but after sometime it slow down from MB TO KB i use mega api key. dont know where the problem is can you tell me how to fix it. i use the latest version.

**Comment by bhavukkalra** [comment]
This proxy list worked for me. I might be using a lot of proxies and also not working ones as well.

but using these proxies list worked - https://tinyurl.com/y48pwptd

**Comment by puneet-khatri** [comment]
@bhavukkalra the link is not working
