### ISSUE TITLE
Clarifications about the "MEGA API KEY ERROR" message on startup

### ISSUE THREAD

**Issue by guixxx** [tonikelope/megabasterd#280]
Hi.

I noticed that in the latest version of MegaBasterd, an error message is displayed if I don't have a MEGA API key set. Additionally, MegaBasterd automatically opens my web browser after I close the dialog. :(

My question is: Is the API key really necessary if I'm just using MegaBasterd to download stuff without an account?

If the above statement is correct, could you please consider implementing one of these options:

* Only display that error message for people that actually have an account added to MegaBasterd.
* **Or**: Maybe display that error after an user adds their account but forgets to add an API key?
* **Or even**: Add two buttons in that error message. One saying "Get a key on MEGA.nz" and the other one saying just "Close". If the user clicks on "Close", nothing happens and MegaBasterd opens like usual. If the user clicks the first button, only then MegaBasterd opens the web browser.

What do you think?
Thanks in advance!

**Comment by tonikelope** [comment]
Hi. The error message is set that way intentionally. The use of a KEY API is not technically mandatory but it is in the terms of use of MEGA (paragraph 16). I've left it optional for the moment, but I don't rule out making it mandatory in the future. Anyway, I will implement the warning message as you suggest in the third option so that it does not open the browser every time MegaBasterd is opened.

Regards.

**Comment by guixxx** [comment]
Thanks for clarifying! Looking forward to test it in the next release :)
