### ISSUE TITLE
Manually Specify Protocol / socks support

### ISSUE THREAD

**Issue by 0-MegaMind-0** [tonikelope/megabasterd#291]
I couldn't figure out if the program supports socks or how to manually specify protocol for the proxy 

while the program says the format is [*]IP:PORT[@user_b64:password_b64]

so i tried  these formats but none of them seem to work 
```
[socks4]1.2.3.4:8090
[socks5]1.2.3.4:8091
[http]1.2.3.4:8092
[https]1.2.3.4:8093
```
tried it in a similar format that other programs use for proxy 
```
socks4://1.2.3.4:8090
socks5://1.2.3.4:8091
http://1.2.3.4:8092
https://1.2.3.4:8093
```

neither of these worked but just use `ip:port` for http proxies works fine.

Is there no way to define protocol or am i just missing something here? 
Also is there socks4/5 support ?

**Comment by Moustafa-desha** [comment]
is it work with you ? not work with me and i need to download file it's very important

**Comment by Moustafa-desha** [comment]
hey man thxs for proxy use HTTP(s) Proxy it work 1.2.3.4 port   8090 
use it in your program will will download with you . it work with me now

**Comment by luthfisolahudin** [comment]
> I couldn't figure out if the program supports socks or how to manually specify protocol for the proxy
> 
> while the program says the format is [*]IP:PORT[@user_b64:password_b64]
> 
> so i tried these formats but none of them seem to work
> 
> ```
> [socks4]1.2.3.4:8090
> [socks5]1.2.3.4:8091
> [http]1.2.3.4:8092
> [https]1.2.3.4:8093
> ```
> 
> tried it in a similar format that other programs use for proxy
> 
> ```
> socks4://1.2.3.4:8090
> socks5://1.2.3.4:8091
> http://1.2.3.4:8092
> https://1.2.3.4:8093
> ```
> 
> neither of these worked but just use `ip:port` for http proxies works fine.
> 
> Is there no way to define protocol or am i just missing something here?
> Also is there socks4/5 support ?

I think the format is like this

if your proxy is HTTP or HTTPS just type IP:port[@username (base64 encoded):password (base64 encoded)]
if your proxy is SOCKS4 or SOCKS5 type *IP:port[@username (base64 encoded):password (base64 encoded)] (with a star symbol in the beginning of the proxy)
and square bracket symbols means if you need it. if don't need it, you don't have to type it

for examples:
*1.2.3.4:8090
*1.2.3.4:8091
1.2.3.4:8092
1.2.3.4:8093

**Comment by BeholdTheKing** [comment]
Sorry I’m slow but it’s the 2nd half that’s been giving me the problems. 

With just: 

*1.2.3.4:port … Proxies with no password it worked just fine. (To my knowledge at least because I never had access to those server said to check the bandwidth traffic.) 

It’s been figuring out how to get higher speed proxies with passwords to work that have been the problem. 

Most recently I’ve tried:

*1.2.3.4:port@user:password

All the attempts doing this failed however. Am I supposed to be adding in the “_b64”? I have a proxy tester where the format is:

1.2.3.4:port:user:password

And the results has them all working so I know it’s not a proxy issue. I’m just trying to figure out if my syntax is still off.
