### ISSUE TITLE
Why is the portable installation of this program not actually portable?

### ISSUE THREAD

**Issue by idgas01** [tonikelope/megabasterd#307]
I asked this question, and instead of getting a response **tonikelope** just closed the issue.

This program is NOT portable.  If you can prove to me that it is a PORTABLE installation, then why not take a minute of explaining how it is portable instead of just closing the issue without saying anything?  But I have already proven that it is NOT portable.

> It creates a bunch of folders like ".megabasterd_old_backups" and ".megabasterd7.40" at this location C:\Users\Brian, even though the program is installed in a completely different location.

Portable App Guidelines:

A portable app works from any device (USB flash drive, portable hard drive, cloud drive, memory card, etc)
A portable app works as you move computers and your drive letter changes
**A portable app is self-contained in a single directory with sub-directories and files within**
A portable app's features continue working as you move computers
 **A portable app doesn't leave files or folders behind except those automatically generated by Windows**
A portable app doesn't leave registry entries behind except those automatically generated by Windows
A portable app is optimized for use on removable drives
A portable app doesn't require additional software on the PC
 A portable app doesn't interfere with software installed on the PC

Your so-called portable installation of megabasterd is NOT self-contained in a single directory, has folders in other directories, and leaves those files and folders behind.

**PLEASE ADDRESS THIS ISSUE INSTEAD OF CLOSING THE ISSUE WITHOUT SAYING ANYTHING.**

**Comment by tonikelope** [comment]
Sorry, it was closed by mistake. Indeed, you are right that by definition an application that calls itself portable should not write files to the system outside of its own "container" or folder. In fact, that's how MegaBasterd worked in its early versions. The reason for the change was when in the releases I started using https://appimage.org/ which did not allow MegaBasterd to write inside the container at runtime. So I changed the logic to create a folder for MegaBasterd in the user's "home" folder where the database of transfers, settings, etc. is stored.

Since appimage is no longer used, when I have time I will modify MegaBasterd so that the portable version stores its data in its own folder.

Sorry for any inconvenience this may have caused you.

Best regards.

**Comment by idgas01** [comment]
Thanks for the response, explanation, and for being willing to make it fully portable in the future.

**Comment by idgas01** [comment]
> Since appimage is no longer used, when I have time I will modify MegaBasterd so that the portable version stores its data in its own folder.

Any news or progress on this?  Will it be implemented in the next update?

**Comment by idgas01** [comment]
@tonikelope

Thank you!
