### ISSUE TITLE
User/Pass Portion of ProxyList

### ISSUE THREAD

**Issue by BeholdTheKing** [tonikelope/megabasterd#321]
> I couldn't figure out if the program supports socks or how to manually specify protocol for the proxy
> 
> while the program says the format is [*]IP:PORT[@user_b64:password_b64]
> 
> so i tried these formats but none of them seem to work
> 
> ```
> [socks4]1.2.3.4:8090
> [socks5]1.2.3.4:8091
> [http]1.2.3.4:8092
> [https]1.2.3.4:8093
> ```
> 
> tried it in a similar format that other programs use for proxy
> 
> ```
> socks4://1.2.3.4:8090
> socks5://1.2.3.4:8091
> http://1.2.3.4:8092
> https://1.2.3.4:8093
> ```
> 
> neither of these worked but just use `ip:port` for http proxies works fine.
> 
> Is there no way to define protocol or am i just missing something here?
> Also is there socks4/5 support ?

I think the format is like this

if your proxy is HTTP or HTTPS just type IP:port[@username (base64 encoded):password (base64 encoded)]
if your proxy is SOCKS4 or SOCKS5 type *IP:port[@username (base64 encoded):password (base64 encoded)] (with a star symbol in the beginning of the proxy)
and square bracket symbols means if you need it. if don't need it, you don't have to type it

for examples:
*1.2.3.4:8090
*1.2.3.4:8091
1.2.3.4:8092
1.2.3.4:8093

_Originally posted by @luthfisolahudin in https://github.com/tonikelope/megabasterd/issues/291#issuecomment-774480622_

***

Thank you for the response, and sorry I’m slow, but it’s the 2nd half of the format that’s been giving me the problems.

With just:

*1.2.3.4:port … Proxies with no password worked just fine. (To my knowledge at least because I never had access to those server side to check the bandwidth traffic.)

It’s been figuring out how to get higher speed proxies with passwords to work that have been my problem.

Most recently I’ve tried:

*1.2.3.4:port@user:password

All the attempts doing this failed however.  Am I supposed to be adding in the “_b64” or "(base64 encoded)"?  I have a proxy tester where the format is:

1.2.3.4:port:user:password

And the results has them all working so I know it’s not a proxy issue.  I’m just trying to figure out if my syntax is still off.

**Comment by luthfisolahudin** [comment]
The user and the password need to be in base64 encoded using base64 encoder like this `https://www.base64encode.org/`.

Examples:
My proxy is `https://1.2.3.4:5678@my_user:my_password`.
Then I put the user, in my case the user is `my_user`, to the base64 encoder. And I copy the encoded user, which will be something like this `bXlfdXNlcg==`.
If yours is different don't worry, it is just because our user is different.
Next, do the same thing to the password, put it in the base64 encoder, and use the encoded password.
After encoding the user and the password, the proxy will be something this `1.2.3.4:5678@bXlfdXNlcg==:bXlfcGFzc3dvcmQ=`

I hope it's clear enough.

**Comment by BeholdTheKing** [comment]
Ahhh there we go.  I didn't even know that was a thing I apologize.  It's working now though thank you kindly.
