### ISSUE TITLE
Sadly Resets Chunks

### ISSUE THREAD

**Issue by baraa272** [tonikelope/megabasterd#34]
Sadly the infinite reset chunks are back on ( 5.51) :(
megabasterd 5.49 sometimes works sometimes resets chunks 
megabasterd 5.26 is working without problems

**Comment by tonikelope** [comment]
Hello. Log?

Regards-

**Comment by baraa272** [comment]
yes sorry for wait 
[log.txt](https://github.com/tonikelope/megabasterd/files/2510046/log.txt)
All love and respect

**Comment by tonikelope** [comment]
Hello. It's not about 5.26 vs 5.51 because Chunkdownloader logic is the same. The problem it's that some files randomly gives error 503 when too much slots are trying to download the same file. I have changed the code to disable the slot when it receives error 503. There is no solution for 503 error, just stop the slot.
