### ISSUE TITLE
Megabasterd closes after startup when AutoClose is enabled and completed downloads still in the list.

### ISSUE THREAD

**Issue by ericziethen** [tonikelope/megabasterd#394]
What is happening is

1. No current downloads
2. Enable AutoClose when all downloads are finished
3. Add only downloads that have been downloaded already, they will all show "same name and same size"
4. Megabasterd will close
5. When starting megabasterd, it still sees the completed downloads, checks them and once done closes again
6. This leads to not being able to do anything

There is one issue open #379 that reported that there is no way to clear the downloads if only already existing files are added.

In addition to that, AutoClose probably shouldn't close if all Megabasterd did was check existing downloads, i.e. nothing actually got downloaded.

**Comment by tonikelope** [comment]
The behavior of the self-closing system has also been modified. If a download is added, it fails due to name collision and there is no more, the program closes. But when reopening that download it will not appear again and the auto close will not be triggered until no more downloads are added. I hope this helps.
