### ISSUE TITLE
Need more information about these numbers

### ISSUE THREAD

**Issue by bagajohny** [tonikelope/megabasterd#456]
I need to know what these numbers represent.

1.  What is the number circled in red colour represents? It doesn't appear all the time but sometimes it appears and then vanishes.
2. Why is the colour of the speed circled in green colour sometimes shown in blue but other times shown in orange colour? When the colour changes to orange the speed of the download decreases.

<a href="https://ibb.co/304jQwR"><img src="https://i.ibb.co/y8dZ7D4/image.png" alt="image" border="0"></a>

**Comment by tonikelope** [comment]
> I need to know what these numbers represent.
> 
>     1. What is the number circled in red colour represents? It doesn't appear all the time but sometimes it appears and then vanishes.
> 
>     2. Why is the colour of the speed circled in green colour sometimes shown in blue but other times shown in orange colour? When the colour changes to orange the speed of the download decreases.
> 
> 
> [![image](https://camo.githubusercontent.com/bc8cb4a5d3c081e36817bcf1c630b6b86b64ca94bd180eebc65c27de89c25498/68747470733a2f2f692e6962622e636f2f7938645a3744342f696d6167652e706e67)](https://ibb.co/304jQwR)

1 Those are the download slots that are failing. Why is a slot failing? Usually because the proxy that was using the slot has given some kind of failure (saturation, timeout, bandwidth exhausted, etc). Other times slots fail when exceeding 10 download slots (some MEGA downloads are limited to 10 slots).

2 The orange color indicates that the download is being done through a proxy that will almost never offer the same speed as a direct download.

Regards.
