### ISSUE TITLE
Proxy list stopped updating

### ISSUE THREAD

**Issue by gibson-kim** [tonikelope/megabasterd#481]
https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt

**Comment by dasauto1** [comment]
I think it is by choice. Happy to be corrected though. It was a great addition to an amazing piece of software.

**Comment by tonikelope** [comment]
The machine I had for testing and filtering MEGA public proxies is down for maintenance and I don't know when it will be able to work again, sorry. In case of not being able to reactivate it I will make public the script to test and filter the MEGA servers so that everyone can do it from their own computer.

Regards.

**Comment by dasauto1** [comment]
Thanks a ton. Script being made available would be great. Appreciate it.

**Comment by tonikelope** [comment]
It's working now.

**Comment by nirmal0001** [comment]
its not updating 
any way to add url insted of proxy 
url return 
correct format of proxy

**Comment by petesimon** [comment]
> https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt

"File not found" error ☹️
