### ISSUE TITLE
Mega/MC APIException error MEGAAPI ERROR: -9

### ISSUE THREAD

**Issue by Auditormadness9** [tonikelope/megabasterd#602]
![image](https://github.com/tonikelope/megabasterd/assets/71278545/dd152194-32c9-43ce-8aea-e409f4059c81)

**Comment by SimplyOCT** [comment]
On top of that, I have this issue for which everything seems to stop until it gets resolved manually. Wish there were some options so that we can opt out this retrying thingy.  Really inconvenient for downloading large folders. 
![image](https://github.com/tonikelope/megabasterd/assets/149765526/17e383a4-8e00-422b-80b6-6b22ca5e1e84)

**Comment by Auditormadness9** [comment]
Issue: Wrong link.
